name: Auto Merge on Label
on:
  pull_request:
    types: [labeled, synchronize]
jobs:
  auto-merge:
    runs-on: ubuntu-latest
    if: github.event.label.name == 'merge' && github.event.pull_request.base.ref == 'main'
    steps:
      - name: checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          fetch-depath: 0

      - name: Setup Git Config
        run: 
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'

      - name: Merge Pull Request
          run:
            git fetch origin main
            git checkout main
            git merge --no-ff ${{ github.event.pull_request.head.sha }} -m "Merge pull request #${{ github.event.pull_request.number }} via GitHub Actions"
            git push origin main
          env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}