name: Auto Merge on Label
on:
  pull_request:
    types: [labeled]
jobs:
  auto-merge:
    runs-on: ubuntu-latest
    if: github.event.label.name == 'merge' && github.event.pull_request.base.ref == 'main'
    steps:
      - name: checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          fetch-depath: 0
      - name: Merge pull request
        run: git merge --no-ff -m 'Merge pull request #${{ github.event.pull_request.number }}' ${{ github.event.pull_request.head.sha }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}