name: Auto Merge on Label
on:
  pull_request:
    types: [labeled, synchronize]
jobs:
  auto-merge:
    runs-on: ubuntu-latest
    if: github.event.label.name == 'merge' && github.event.pull_request.base.ref == 'main'
    steps:
      - name: checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          fetch-depath: 0

      - name: Merge Pull Request
            uses: actions/github-script@v6
            with:
              github-token: ${{secrets.GITHUB_TOKEN}}
              script: |
                github.rest.pulls.merge({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  pull_number: context.issue.number
                })