name: List Directory Structure
on:
  pull_request:
    types: [opened]
jobs:
  list-directory:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v3

      - name: List Directory Structure
        run: ls -R